export const allChartData = {
  "2020": {
    lineChart: [
      { month: "January", desktop: 100, mobile: 50 },
      { month: "February", desktop: 150, mobile: 70 },
      { month: "March", desktop: 120, mobile: 60 },
      { month: "April", desktop: 90, mobile: 80 },
      { month: "May", desktop: 180, mobile: 100 },
      { month: "June", desktop: 160, mobile: 90 },
    ],
    barChart: [
      { month: "January", totalBooks: 100 },
      { month: "February", totalBooks: 150 },
      { month: "March", totalBooks: 120 },
      { month: "April", totalBooks: 90 },
      { month: "May", totalBooks: 180 },
      { month: "June", totalBooks: 160 },
    ],
  },
  "2021": {
    lineChart: [
      { month: "January", desktop: 120, mobile: 60 },
      { month: "February", desktop: 180, mobile: 90 },
      { month: "March", desktop: 150, mobile: 75 },
      { month: "April", desktop: 100, mobile: 100 },
      { month: "May", desktop: 200, mobile: 120 },
      { month: "June", desktop: 190, mobile: 110 },
    ],
    barChart: [
      { month: "January", totalBooks: 120 },
      { month: "February", totalBooks: 180 },
      { month: "March", totalBooks: 150 },
      { month: "April", totalBooks: 100 },
      { month: "May", totalBooks: 200 },
      { month: "June", totalBooks: 190 },
    ],
  },
  "2022": {
    lineChart: [
      { month: "January", desktop: 140, mobile: 70 },
      { month: "February", desktop: 200, mobile: 100 },
      { month: "March", desktop: 170, mobile: 85 },
      { month: "April", desktop: 110, mobile: 110 },
      { month: "May", desktop: 220, mobile: 130 },
      { month: "June", desktop: 210, mobile: 120 },
    ],
    barChart: [
      { month: "January", totalBooks: 140 },
      { month: "February", totalBooks: 200 },
      { month: "March", totalBooks: 170 },
      { month: "April", totalBooks: 110 },
      { month: "May", totalBooks: 220 },
      { month: "June", totalBooks: 210 },
    ],
  },
  "2023": {
    lineChart: [
      { month: "January", desktop: 160, mobile: 80 },
      { month: "February", desktop: 220, mobile: 110 },
      { month: "March", desktop: 190, mobile: 95 },
      { month: "April", desktop: 120, mobile: 120 },
      { month: "May", desktop: 240, mobile: 140 },
      { month: "June", desktop: 230, mobile: 130 },
    ],
    barChart: [
      { month: "January", totalBooks: 160 },
      { month: "February", totalBooks: 220 },
      { month: "March", totalBooks: 190 },
      { month: "April", totalBooks: 120 },
      { month: "May", totalBooks: 240 },
      { month: "June", totalBooks: 230 },
    ],
  },
  "2024": {
    lineChart: [
      { month: "January", desktop: 10, mobile: 80 },
      { month: "February", desktop: 305, mobile: 200 },
      { month: "March", desktop: 237, mobile: 120 },
      { month: "April", desktop: 73, mobile: 190 },
      { month: "May", desktop: 209, mobile: 130 },
      { month: "June", desktop: 214, mobile: 140 },
    ],
    barChart: [
      { month: "January", totalBooks: 186 },
      { month: "February", totalBooks: 305 },
      { month: "March", totalBooks: 237 },
      { month: "April", totalBooks: 73 },
      { month: "May", totalBooks: 209 },
      { month: "June", totalBooks: 214 },
    ],
  },
  "2025": {
    lineChart: [
      { month: "January", desktop: 200, mobile: 90 },
      { month: "February", desktop: 320, mobile: 210 },
      { month: "March", desktop: 250, mobile: 130 },
      { month: "April", desktop: 80, mobile: 200 },
      { month: "May", desktop: 220, mobile: 140 },
      { month: "June", desktop: 230, mobile: 150 },
    ],
    barChart: [
      { month: "January", totalBooks: 200 },
      { month: "February", totalBooks: 320 },
      { month: "March", totalBooks: 250 },
      { month: "April", totalBooks: 80 },
      { month: "May", totalBooks: 220 },
      { month: "June", totalBooks: 230 },
    ],
  },
  "2026": {
    lineChart: [
      { month: "January", desktop: 210, mobile: 95 },
      { month: "February", desktop: 330, mobile: 220 },
      { month: "March", desktop: 260, mobile: 140 },
      { month: "April", desktop: 90, mobile: 210 },
      { month: "May", desktop: 230, mobile: 150 },
      { month: "June", desktop: 240, mobile: 160 },
    ],
    barChart: [
      { month: "January", totalBooks: 210 },
      { month: "February", totalBooks: 330 },
      { month: "March", totalBooks: 260 },
      { month: "April", totalBooks: 90 },
      { month: "May", totalBooks: 230 },
      { month: "June", totalBooks: 240 },
    ],
  },
  "2027": {
    lineChart: [
      { month: "January", desktop: 220, mobile: 100 },
      { month: "February", desktop: 340, mobile: 230 },
      { month: "March", desktop: 270, mobile: 150 },
      { month: "April", desktop: 100, mobile: 220 },
      { month: "May", desktop: 240, mobile: 160 },
      { month: "June", desktop: 250, mobile: 170 },
    ],
    barChart: [
      { month: "January", totalBooks: 220 },
      { month: "February", totalBooks: 340 },
      { month: "March", totalBooks: 270 },
      { month: "April", totalBooks: 100 },
      { month: "May", totalBooks: 240 },
      { month: "June", totalBooks: 250 },
    ],
  },
};
